# Generated by Django 6.1 on 2026-08-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(default='onboarding', max_length=32)),
                ('progress_pct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=128, unique=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee_roles',
            },
        ),
        migrations.CreateModel(
            name='OnboardingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(unique=True)),
                ('phase_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'onboarding_phases',
            },
        ),
        migrations.CreateModel(
            name='ClaimSystemVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_text', models.TextField()),
                ('verified_by', models.CharField(default='Admin User', max_length=128)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='api.client')),
            ],
            options={
                'db_table': 'claim_system_verifications',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(default='Admin User', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.client')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=128)),
                ('employee_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('after_hours_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.client')),
            ],
            options={
                'db_table': 'client_contacts',
            },
        ),
        migrations.CreateModel(
            name='ClientTransferConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='SFTP', max_length=64)),
                ('watched_folder_sftp', models.BooleanField(default=False)),
                ('keys_exchanged', models.BooleanField(default=False)),
                ('no_change_to_client_system', models.BooleanField(default=False)),
                ('setup_status', models.CharField(default='Configured', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_configs', to='api.client')),
            ],
            options={
                'db_table': 'client_transfer_configurations',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('step_key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_type', models.CharField(default='upload_template', max_length=64)),
                ('download_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('download_extension', models.CharField(blank=True, max_length=16, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.onboardingphase')),
            ],
            options={
                'db_table': 'onboarding_step_definitions',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='StepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('author', models.CharField(default='Admin User', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.onboardingstepdefinition')),
            ],
            options={
                'db_table': 'step_notes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StepSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.CharField(max_length=32)),
                ('scheduled_time', models.CharField(max_length=32)),
                ('timezone', models.CharField(default='ET', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.client')),
            ],
            options={
                'db_table': 'step_schedules',
            },
        ),
        migrations.CreateModel(
            name='StepTextSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField()),
                ('submitted_by', models.CharField(default='Admin User', max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_submissions', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_submissions', to='api.onboardingstepdefinition')),
            ],
            options={
                'db_table': 'step_text_submissions',
            },
        ),
        migrations.CreateModel(
            name='StepUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.IntegerField(default=0)),
                ('validation_status', models.CharField(default='PASSED', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='api.onboardingstepdefinition')),
            ],
            options={
                'db_table': 'step_uploads',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='WAITING', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='api.onboardingstepdefinition')),
            ],
            options={
                'db_table': 'client_step_statuses',
                'unique_together': {('client', 'step')},
            },
        ),
    ]
