# Generated by Django 6.1 on 2026-08-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='claims_system',
            field=models.CharField(default='Vendor hosted', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_file',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='live_since',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.CharField(default='Vikram J.', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='Waiting on client', max_length=64),
        ),
    ]
