# Generated by Django 6.1 on 2026-08-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_claims_system_client_code_client_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLiveStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('step_key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_type', models.CharField(max_length=64)),
                ('download_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('download_extension', models.CharField(default='pdf', max_length=16)),
            ],
            options={
                'db_table': 'golive_step_definitions',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=128)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=64)),
                ('user_agent', models.CharField(default='Mozilla/5.0', max_length=255)),
                ('status', models.CharField(default='SUCCESS', max_length=32)),
                ('session_token', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'login_history',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(default='SYSTEM', max_length=64),
        ),
        migrations.AlterField(
            model_name='clienttransferconfig',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_config', to='api.client'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=512)),
                ('document_type', models.CharField(default='General', max_length=128)),
                ('direction', models.CharField(default='Client → OneSmarter', max_length=64)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=128)),
                ('status', models.CharField(default='Executed', max_length=32)),
                ('uploaded_by', models.CharField(default='Admin User', max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_details', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.client')),
            ],
            options={
                'db_table': 'client_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientGoLiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('entered_by', models.CharField(default='Admin User', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='golive_comment', to='api.client')),
            ],
            options={
                'db_table': 'client_golive_comments',
            },
        ),
        migrations.CreateModel(
            name='ClientGoLiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.CharField(max_length=32)),
                ('production_time', models.CharField(blank=True, max_length=32, null=True)),
                ('entered_by', models.CharField(default='Admin User', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='golive_schedule', to='api.client')),
            ],
            options={
                'db_table': 'client_golive_schedules',
            },
        ),
        migrations.CreateModel(
            name='ClientGoLiveSFTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_folder_sftp', models.BooleanField(default=False)),
                ('keys_exchanged', models.BooleanField(default=False)),
                ('no_change_to_client_system', models.BooleanField(default=False)),
                ('in_bounded_action', models.BooleanField(default=False)),
                ('out_bounded_action', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='golive_sftp', to='api.client')),
            ],
            options={
                'db_table': 'client_golive_sftp',
            },
        ),
        migrations.CreateModel(
            name='ClientTestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftp_host', models.CharField(default='sftp-test.onesmarter.internal', max_length=255)),
                ('sftp_port', models.IntegerField(default=22)),
                ('sftp_username', models.CharField(default='sandbox_admin', max_length=128)),
                ('watched_folder', models.CharField(default='/inbound/835_test', max_length=255)),
                ('keys_status', models.CharField(default='Separate from Production', max_length=128)),
                ('mpl_delivery_blocked', models.BooleanField(default=True)),
                ('archive_retention_days', models.IntegerField(default=90)),
                ('test_status', models.CharField(default='In Progress', max_length=64)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_environment', to='api.client')),
            ],
            options={
                'db_table': 'client_test_environments',
            },
        ),
        migrations.CreateModel(
            name='ClientGoLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='WAITING', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golive_statuses', to='api.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='api.golivestepdefinition')),
            ],
            options={
                'db_table': 'client_golive_statuses',
                'unique_together': {('client', 'step')},
            },
        ),
    ]
